using System.Collections;
using System.Collections.Generic;

namespace AngeliA;


/// <summary>
/// Representation of game asset folder
/// </summary>
public class Universe {

	/// <summary>
	/// Built-in universe of the current game
	/// </summary>
	public static Universe BuiltIn { get; private set; }
	/// <summary>
	/// Info.json of the built-in universe
	/// </summary>
	public static UniverseInfo BuiltInInfo { get; private set; }

	// Universe Path
	/// <summary>
	/// Root folder path of this universe
	/// </summary>
	public string UniverseRoot { get; private set; }
	/// <summary>
	/// Artwork sheets root folder path
	/// </summary>
	public string SheetRoot { get; private set; }
	/// <summary>
	/// Built-in artwork sheet file path. This file is generated by the game engine.
	/// </summary>
	public string BuiltInSheetPath { get; private set; }
	/// <summary>
	/// Artwork sheet file path. This file is painted by the developer of the game.
	/// </summary>
	public string GameSheetPath { get; private set; }
	/// <summary>
	/// Info.json file path
	/// </summary>
	public string InfoPath { get; private set; }
	/// <summary>
	/// Path of the folder that hold conversation files
	/// </summary>
	public string ConversationRoot { get; private set; }
	/// <summary>
	/// Root meta folder path. This folder hold random text data.
	/// </summary>
	public string UniverseMetaRoot { get; private set; }
	/// <summary>
	/// Map root folder path. Map inside this folder should not be edit by the player.
	/// </summary>
	public string BuiltInMapRoot { get; private set; }
	/// <summary>
	/// Folder that holds the localization files
	/// </summary>
	public string LanguageRoot { get; private set; }
	/// <summary>
	/// Folder that holds BGM audio files
	/// </summary>
	public string MusicRoot { get; private set; }
	/// <summary>
	/// Folder that holds SFX audio files
	/// </summary>
	public string SoundRoot { get; private set; }
	/// <summary>
	/// Folder that holds font files
	/// </summary>
	public string FontRoot { get; private set; }
	/// <summary>
	/// Folder that holds character movement config json files
	/// </summary>
	public string CharacterMovementConfigRoot { get; private set; }
	/// <summary>
	/// Data from Info.json file
	/// </summary>
	public UniverseInfo Info { get; private set; }

	// User Saving Path
	/// <summary>
	/// Current selected saving slot index
	/// </summary>
	public int CurrentSavingSlot { get; private set; }
	/// <summary>
	/// Root of the saving folder
	/// </summary>
	public string SavingRoot { get; private set; }
	/// <summary>
	/// Folder path of the current selected slot
	/// </summary>
	public string SlotRoot { get; private set; }
	/// <summary>
	/// Meta root folder path of the current selected slot
	/// </summary>
	public string SlotMetaRoot { get; private set; }
	/// <summary>
	/// Map root folder of the current selected slot. Maps inside this folder can be edit by player
	/// </summary>
	public string SlotUserMapRoot { get; private set; }
	/// <summary>
	/// Root folder path holds the rendering config json files for pose characters
	/// </summary>
	public string SlotCharacterRenderingConfigRoot { get; private set; }
	/// <summary>
	/// Root folder path holds the inventory files
	/// </summary>
	public string SlotInventoryRoot { get; private set; }


	// MSG
	[OnGameInitialize(int.MinValue)]
	internal static void OnGameInitializeMin () {
		BuiltIn = LoadFromFile(AngePath.BuiltInUniverseRoot);
		BuiltInInfo = BuiltIn.Info;
		AngePath.SetCurrentUserPath(BuiltIn.Info.DeveloperName, BuiltIn.Info.ProductName);
	}


	// API
	/// <summary>
	/// Create a new universe instance from file
	/// </summary>
	public static Universe LoadFromFile (string universeFolder, bool useBuiltInSavingRoot = true) {
		string infoPath = AngePath.GetUniverseInfoPath(universeFolder);
		var result = new Universe {
			UniverseRoot = universeFolder,
			SheetRoot = AngePath.GetSheetRoot(universeFolder),
			BuiltInSheetPath = AngePath.GetBuiltInSheetPath(universeFolder),
			GameSheetPath = AngePath.GetGameSheetPath(universeFolder),
			ConversationRoot = AngePath.GetConversationRoot(universeFolder),
			UniverseMetaRoot = AngePath.GetUniverseMetaRoot(universeFolder),
			LanguageRoot = AngePath.GetLanguageRoot(universeFolder),
			BuiltInMapRoot = AngePath.GetMapRoot(universeFolder),
			InfoPath = infoPath,
			Info = JsonUtil.LoadOrCreateJsonFromPath<UniverseInfo>(infoPath),
			MusicRoot = AngePath.GetUniverseMusicRoot(universeFolder),
			SoundRoot = AngePath.GetUniverseSoundRoot(universeFolder),
			FontRoot = AngePath.GetUniverseFontRoot(universeFolder),
			CharacterMovementConfigRoot = AngePath.GetCharacterMovementConfigRoot(universeFolder),
		};

		// Load Saving & Slot
		int currentSlot = 0;
		string savingRoot = useBuiltInSavingRoot ?
			Util.CombinePaths(AngePath.GetPersistentDataPath(result.Info.DeveloperName, result.Info.ProductName), "Saving") :
			Util.CombinePaths(universeFolder, "Saving");
		string currentSlotStr = Util.FileToText(Util.CombinePaths(savingRoot, "CurrentSlot.txt"));
		if (!string.IsNullOrWhiteSpace(currentSlotStr) && int.TryParse(currentSlotStr, out currentSlot)) {
			currentSlot = currentSlot.GreaterOrEquelThanZero();
		}
		result.SetSavingRoot(savingRoot, currentSlot);

		// Create Folders
		Util.CreateFolder(result.ConversationRoot);
		Util.CreateFolder(result.UniverseMetaRoot);
		Util.CreateFolder(result.BuiltInMapRoot);
		Util.CreateFolder(result.LanguageRoot);
		Util.CreateFolder(result.SlotRoot);
		Util.CreateFolder(result.SlotMetaRoot);
		Util.CreateFolder(result.SlotUserMapRoot);
		Util.CreateFolder(result.MusicRoot);
		Util.CreateFolder(result.SoundRoot);
		Util.CreateFolder(result.FontRoot);
		Util.CreateFolder(result.SlotCharacterRenderingConfigRoot);
		Util.CreateFolder(result.CharacterMovementConfigRoot);
		Util.CreateFolder(result.SlotInventoryRoot);
		Util.CreateFolder(result.SheetRoot);

		return result;
	}


	/// <summary>
	/// Change saving slot
	/// </summary>
	/// <param name="newSlot">Slot index</param>
	/// <param name="forceReload">Perform this function even the "newSlot" is same with current</param>
	public void ReloadSavingSlot (int newSlot, bool forceReload = false) {
		if (!forceReload && newSlot == CurrentSavingSlot) return;
		OrderedAttribute.InvokeAsAutoOrderingTask<BeforeSavingSlotChanged>();
		CurrentSavingSlot = newSlot;
		SetSavingRoot(SavingRoot, newSlot);
		OrderedAttribute.InvokeAsAutoOrderingTask<OnSavingSlotChanged>();
	}


	/// <summary>
	/// Set saving data of the universe instance
	/// </summary>
	public void SetSavingRoot (string newSavingRoot, int slot) {
		SavingRoot = newSavingRoot;
		SlotRoot = AngePath.GetSlotRoot(newSavingRoot, slot);
		SlotMetaRoot = AngePath.GetSlotMetaRoot(newSavingRoot, slot);
		SlotInventoryRoot = AngePath.GetSlotInventoryRoot(newSavingRoot, slot);
		SlotUserMapRoot = AngePath.GetSlotUserMapRoot(newSavingRoot, slot);
		SlotCharacterRenderingConfigRoot = AngePath.GetSlotMetaCharacterConfigRoot(newSavingRoot, slot);
	}


}
