using System.Collections;
using System.Collections.Generic;


namespace AngeliaFramework {
	[RequireSpriteFromField]
	public static class BuiltInIcon {

		public static readonly SpriteCode NPC = "NPC";
		public static readonly SpriteCode WALLPAPER_CLOUD = "WallpaperCloud";
		public static readonly SpriteCode PLUS_16 = "Plus16";
		public static readonly SpriteCode EQUAL_16 = "Equal16";
		public static readonly SpriteCode QUESTION_MARK_16 = "QuestionMark16";
		public static readonly SpriteCode GAMEPAD_BODY = "GamePad Body";
		public static readonly SpriteCode GAMEPAD_EAST = "k_Gamepad East";
		public static readonly SpriteCode GAMEPAD_UP = "k_Gamepad Up";
		public static readonly SpriteCode UPARROW = "k_UpArrow";
		public static readonly SpriteCode FRAME_16 = "Frame16";
		public static readonly SpriteCode MENU_SELECTION_MARK = "Menu Selection Mark";
		public static readonly SpriteCode SOFT_LINE_H = "Soft Line H";
		public static readonly SpriteCode SOFT_LINE_V = "Soft Line V";
		public static readonly SpriteCode GAMEPAD_START = "k_Gamepad Start";
		public static readonly SpriteCode GAMEPAD_SELECT = "k_Gamepad Select";
		public static readonly SpriteCode ITEM_ICON_ITEM = "ItemIcon.Item";
		public static readonly SpriteCode ITEM_ICON_JEWELRY = "ItemIcon.Jewelry";
		public static readonly SpriteCode ITEM_ICON_ARMOR = "ItemIcon.Armor";
		public static readonly SpriteCode ICON_BODY_PART_HAIR = "Icon.BodyPart.Hair";
		public static readonly SpriteCode ICON_BODY_PART_ARM_HAND = "Icon.BodyPart.ArmHand";
		public static readonly SpriteCode ICON_SUIT_BODYSUIT = "Icon.Suit.Bodysuit";
		public static readonly SpriteCode DOTTED_LINE_16_SMOOTH = "DottedLine16Smooth";
		public static readonly SpriteCode DOTTED_LINE_16 = "DottedLine16";
		public static readonly SpriteCode FRAME_HOLLOW_16 = "FrameHollow16";
		public static readonly SpriteCode GAMEPAD_SOUTH = "k_Gamepad South";
		public static readonly SpriteCode DOWN_ARROW = "k_DownArrow";
		public static readonly SpriteCode GAMEPAD_DOWN = "k_Gamepad Down";
		public static readonly SpriteCode ITEM_ICON_HELMET = "ItemIcon.Helmet";
		public static readonly SpriteCode ITEM_ICON_SHOES = "ItemIcon.Shoes";
		public static readonly SpriteCode ITEM_ICON_FOOD = "ItemIcon.Food";
		public static readonly SpriteCode ICON_BODY_PART_LEG_FOOT = "Icon.BodyPart.LegFoot";
		public static readonly SpriteCode ICON_BODY_PART_BODY = "Icon.BodyPart.Body";
		public static readonly SpriteCode ICON_SUIT_HAT = "Icon.Suit.Hat";
		public static readonly SpriteCode ICON_BODY_PART_HORN = "Icon.BodyPart.Horn";
		public static readonly SpriteCode HINT_BUTTON = "Hint Button";
		public static readonly SpriteCode GAMEPAD_WEST = "k_Gamepad West";
		public static readonly SpriteCode GAMEPAD_LEFT = "k_Gamepad Left";
		public static readonly SpriteCode LEFT_ARROW = "k_LeftArrow";
		public static readonly SpriteCode TRIANGLE_13 = "Triangle13";
		public static readonly SpriteCode GAMEPAD_NORTH = "k_Gamepad North";
		public static readonly SpriteCode GAMEPAD_RIGHT = "k_Gamepad Right";
		public static readonly SpriteCode RIGHT_ARROW = "k_RightArrow";
		public static readonly SpriteCode TRIANGLE_RIGHT_13 = "TriangleRight13";
		public static readonly SpriteCode ITEM_ICON_WEAPON = "ItemIcon.Weapon";
		public static readonly SpriteCode ITEM_ICON_GLOVES = "ItemIcon.Gloves";
		public static readonly SpriteCode ICON_BODY_PART_HEAD = "Icon.BodyPart.Head";
		public static readonly SpriteCode ICON_BODY_PART_FACE = "Icon.BodyPart.Face";
		public static readonly SpriteCode ICON_SUIT_SHOES = "Icon.Suit.Shoes";
		public static readonly SpriteCode ICON_BODY_PART_TAIL = "Icon.BodyPart.Tail";
		public static readonly SpriteCode ICON_BODY_PART_WING = "Icon.BodyPart.Wing";
		public static readonly SpriteCode GAMEPAD_HINT_LEFT = "GamePad Hint Left";
		public static readonly SpriteCode GAMEPAD_HINT_SELECT = "GamePad Hint Select";
		public static readonly SpriteCode GAMEPAD_HINT_UP = "GamePad Hint Up";
		public static readonly SpriteCode GAMEPAD_HINT_RIGHT = "GamePad Hint Right";
		public static readonly SpriteCode GAMEPAD_HINT_START = "GamePad Hint Start";
		public static readonly SpriteCode GAMEPAD_HINT_A = "GamePad Hint A";
		public static readonly SpriteCode GAMEPAD_HINT_B = "GamePad Hint B";
		public static readonly SpriteCode GAMEPAD_HINT_DOWN = "GamePad Hint Down";
		public static readonly SpriteCode CIRCLE_16 = "Circle16";
		public static readonly SpriteCode ICON_BODY_PART_EAR = "Icon.BodyPart.Ear";
		public static readonly SpriteCode ICON_SUIT_GLOVE = "Icon.Suit.Glove";
		public static readonly SpriteCode ICON_SUIT_PANTS = "Icon.Suit.Pants";
		public static readonly SpriteCode ICON_BODY_PART_SKIN_COLOR = "Icon.BodyPart.SkinColor";
		public static readonly SpriteCode ICON_BODY_PART_HAIR_COLOR = "Icon.BodyPart.HairColor";
		public static readonly SpriteCode ICON_BRUSH = "Icon Brush";
		public static readonly SpriteCode ICON_TRIANGLE_UP = "Icon TriangleUp";
		public static readonly SpriteCode ICON_TRIANGLE_DOWN = "Icon TriangleDown";
		public static readonly SpriteCode ICON_TRIANGLE_LEFT = "Icon TriangleLeft";
		public static readonly SpriteCode ICON_TRIANGLE_RIGHT = "Icon TriangleRight";
		public static readonly SpriteCode ICON_MAP = "Icon Map";
		public static readonly SpriteCode UI_ITEM_FRAME = "UI.ItemFrame";
		public static readonly SpriteCode UI_DARK_BUTTON = "UI.DarkButton";
		public static readonly SpriteCode UI_DARK_BUTTON_DOWN = "UI.DarkButtonDown";
		public static readonly SpriteCode UI_BUTTON = "UI.Button";
		public static readonly SpriteCode UI_HOLO_BUTTON = "UI.HoloButton";
		public static readonly SpriteCode UI_BUTTON_DOWN = "UI.ButtonDown";
		public static readonly SpriteCode ICON_SEARCH = "Icon.Search";
		public static readonly SpriteCode MENU_ARROW_MARK = "Menu Arrow Mark";
		public static readonly SpriteCode MENU_MORE_MARK = "Menu More Mark";
		public static readonly SpriteCode ICON_REFRESH = "Icon Refresh";
		public static readonly SpriteCode ICON_GAMEPAD = "Icon Gamepad";
		public static readonly SpriteCode CHECK_MARK_32 = "CheckMark32";
		public static readonly SpriteCode CHECK_MARK_16 = "CheckMark16";
		public static readonly SpriteCode ICON_BODYPART_HEIGHT = "Icon.BodyPart.Height";
		public static readonly SpriteCode GAMEPAD_LEFT_TRIGGER = "k_Gamepad LeftTrigger";
		public static readonly SpriteCode GAMEPAD_RIGHT_TRIGGER = "k_Gamepad RightTrigger";
		public static readonly SpriteCode GAMEPAD_LEFT_SHOULDER = "k_Gamepad LeftShoulder";
		public static readonly SpriteCode GAMEPAD_RIGHT_SHOULDER = "k_Gamepad RightShoulder";
		public static readonly SpriteCode UI_TAB = "UI.Tab";
		public static readonly SpriteCode ICON_STAR = "Icon.Star";
		public static readonly SpriteCode ICON_MENU = "Icon.Menu";
		public static readonly SpriteCode ICON_PALETTE = "Icon.Palette";
		public static readonly SpriteCode ICON_FILE = "Icon.File";
		public static readonly SpriteCode ICON_ATLAS = "Icon.Atlas";
		public static readonly SpriteCode ICON_SPRITE = "Icon.Sprite";

	}
}
